import { useMemo, useState } from 'react'
import type { Activity } from '../types/activity'
import type { ActivityAttempt, TeacherDashboard } from '../types/platform'

interface TeacherPageProps { dashboard: TeacherDashboard; onCreateActivity: (activity: Activity) => void; onBack: () => void }

export function TeacherPage({ dashboard, onCreateActivity, onBack }: TeacherPageProps) {
  const [selected, setSelected] = useState<ActivityAttempt | null>(dashboard.attempts[0] ?? null)
  const [title, setTitle] = useState('Nova atividade')
  const student = selected && dashboard.students.find((item) => item.id === selected.studentId)
  const activity = selected && dashboard.activities.find((item) => item.id === selected.activityId)
  const create = () => { const base = dashboard.activities[0]; if (!base || !title.trim()) return; onCreateActivity({ ...base, id: `atividade-${crypto.randomUUID()}`, slug: title.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-'), title: title.trim(), description: 'Atividade criada pelo professor.', isFeatured: false, status: 'published' }) }
  const stats = useMemo(() => [{ label: 'Alunos participantes', value: dashboard.students.length }, { label: 'Atividades', value: dashboard.activities.length }, { label: 'Média de pontuação', value: dashboard.averageScore }, { label: 'Concluídas', value: dashboard.completedAttempts }], [dashboard])
  return <main className="teacher-page"><header className="home-header"><div className="brand"><span className="brand-mark">V</span>Painel docente</div><button className="link-button" onClick={onBack}>Área do aluno</button></header><section className="teacher-content"><h1>Acompanhamento de aprendizagem</h1><div className="stats-grid">{stats.map((stat) => <article key={stat.label}><strong>{stat.value}</strong><span>{stat.label}</span></article>)}</div><div className="teacher-grid"><section><h2>Turmas</h2>{dashboard.classes.map((classroom) => <p key={classroom.id}>{classroom.name} <small>({classroom.code})</small></p>)}<h2>Tentativas</h2>{dashboard.attempts.map((attempt) => <button className="attempt-row" key={attempt.id} onClick={() => setSelected(attempt)}>{dashboard.students.find((item) => item.id === attempt.studentId)?.displayName} · {dashboard.activities.find((item) => item.id === attempt.activityId)?.title} <strong>{attempt.currentScore}</strong></button>)}</section><section className="attempt-detail"><h2>Detalhe do aluno</h2>{selected && student && activity ? <><p><strong>{student.displayName}</strong> · {student.code}</p><p>{activity.title} · {selected.status} · {selected.currentScore} pontos</p><h3>Documento atual</h3><pre>{JSON.stringify(selected.documents.at(-1)?.content, null, 2)}</pre><h3>Verificações</h3>{selected.verificationRuns.map((run) => <p key={run.id}>{new Date(run.createdAt).toLocaleTimeString('pt-BR')} — {run.score} pontos</p>)}<h3>Timeline pedagógica</h3>{selected.events.map((event) => <p key={event.id}>{new Date(event.timestamp).toLocaleTimeString('pt-BR')} — {event.type}</p>)}</> : <p>Selecione uma tentativa para ver o acompanhamento.</p>}</section></div><section className="creator-card"><h2>Criador de atividades — MVP</h2><p>Cria uma cópia configurável da atividade-base; requisitos e dicas podem ser evoluídos neste mesmo modelo de dados.</p><label>Título<input value={title} onChange={(event) => setTitle(event.target.value)} /></label><button className="primary-button" onClick={create}>Criar atividade</button></section></section></main>
}
